# render.yml
services:
  - type: web
    name: web-craft-server
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Render will provide the actual port in an environment variable
    healthCheckPath: "/health"  # Adjust according to your app's health check endpoint
    autoDeploy: true
    disk:
      - name: persistent_storage
        mountPath: /data
        sizeGB: 1

# Optional: background worker configuration (if needed)
jobs:
  - type: worker
    name: web-craft-worker
    env: node
    buildCommand: "npm install"
    startCommand: "node index.js"  # Replace with your worker's entry point if different
